# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            IC Sulam
tagline:          Unstandard Deviations
url:              http://icsulam.github.io/
paginate:         1
baseurl:          /
author:
  name:           Ian Sulam
  url:            
  email:          ian.sulam@gmail.com

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/icsulam/icsulam.github.io
